"""Claude/Cursor agent plugin for hierarchical configuration management."""

import asyncio
from pathlib import Path

from agent_manager.output import MessageType, VerbosityLevel, message
from agent_manager.plugins.agents import AbstractAgent
from claude_agent_sdk import query


class Agent(AbstractAgent):
    """Agent for managing Claude/Cursor configuration from hierarchical repositories."""

    agent_directory: Path = Path.joinpath(AbstractAgent.home_directory, ".claude")

    def register_hooks(self) -> None:
        """Register Claude-specific hooks for file processing."""
        # Register TextMerger for .cursorrules and .clinerules files (concatenation)
        from agent_manager.plugins.mergers.text_merger import TextMerger

        self.merger_registry.register_filename(".cursorrules", TextMerger)
        self.merger_registry.register_filename(".clinerules", TextMerger)

        # Pre-merge: Clean up markdown files
        self.pre_merge_hooks["*.md"] = self._clean_markdown
        self.pre_merge_hooks[".cursorrules*"] = self._validate_cursorrules
        self.pre_merge_hooks[".clinerules*"] = self._validate_cursorrules

        # Post-merge: Add metadata header to merged files
        self.post_merge_hooks["*"] = self._add_metadata_header

    def _clean_markdown(self, content: str, entry: dict, file_path: Path) -> str:
        """Clean up markdown content before merging.

        Args:
            content: File content
            entry: Hierarchy entry
            file_path: Path to source file

        Returns:
            Cleaned content
        """
        # Strip trailing whitespace and ensure single newline at end
        content = content.rstrip() + "\n"
        message(f"    Cleaned markdown from {entry['name']}", MessageType.DEBUG, VerbosityLevel.DEBUG)
        return content

    def _validate_cursorrules(self, content: str, entry: dict, file_path: Path) -> str:
        """Validate cursorrules/clinerules content.

        Args:
            content: File content
            entry: Hierarchy entry
            file_path: Path to source file

        Returns:
            Validated content
        """
        # Basic validation: ensure not empty
        if not content.strip():
            message(f"    Empty cursorrules file in {entry['name']}", MessageType.WARNING, VerbosityLevel.ALWAYS)
        return content

    def _add_metadata_header(self, content: str, file_name: str, sources: list[str]) -> str:
        """Add metadata header to merged files with appropriate comment syntax.

        Args:
            content: Merged content
            file_name: Output filename
            sources: List of source hierarchy levels

        Returns:
            Content with metadata header
        """
        # Determine comment style based on file extension
        file_lower = file_name.lower()

        # JSON doesn't support comments, skip header
        if file_lower.endswith(".json"):
            return content

        # Use appropriate comment syntax
        if file_lower.endswith((".yaml", ".yml", ".txt", ".py", ".sh", ".cursorrules", ".clinerules")):
            # Hash-style comments for YAML, text, and shell scripts
            comment_start = "# "
            comment_end = ""
        elif file_lower.endswith((".md", ".markdown", ".html", ".xml")):
            # HTML-style comments for Markdown and HTML
            comment_start = "<!-- "
            comment_end = " -->"
        else:
            # Default to hash comments for unknown types
            comment_start = "# "
            comment_end = ""

        # Build header with appropriate comment syntax
        header = f"{comment_start}Generated by agent-manager{comment_end}\n"
        header += f"{comment_start}File: {file_name}{comment_end}\n"
        header += f"{comment_start}Sources: {' → '.join(sources)}{comment_end}\n"
        header += (
            f"{comment_start}Hierarchy: {sources[0]} (lowest) to {sources[-1]} (highest priority){comment_end}\n\n"
        )

        return header + content

    async def _run_claude_init(self) -> None:
        """Run Claude SDK initialization (async helper)."""
        async for msg in query(prompt="/init"):
            message(f"  {msg}", MessageType.INFO, VerbosityLevel.EXTRA_VERBOSE)

    def _initialize(self) -> None:
        """Initialize the Claude agent directory using Claude SDK."""
        # Check if already initialized
        if self.agent_directory.exists():
            message(
                f"Claude agent directory already exists: {self.agent_directory}",
                MessageType.DEBUG,
                VerbosityLevel.DEBUG,
            )
            return

        message(
            f"Initializing Claude agent directory: {self.agent_directory}",
            MessageType.INFO,
            VerbosityLevel.EXTRA_VERBOSE,
        )
        message("Running Claude SDK initialization...", MessageType.INFO, VerbosityLevel.EXTRA_VERBOSE)

        try:
            # Use Claude SDK to initialize with all defaults
            asyncio.run(self._run_claude_init())

            # Ensure our directory exists for merged configurations
            self.agent_directory.mkdir(parents=True, exist_ok=True)
            message(f"✓ Claude agent initialized at {self.agent_directory}", MessageType.SUCCESS, VerbosityLevel.ALWAYS)
        except Exception as e:
            message(f"Claude SDK initialization failed: {e}", MessageType.WARNING, VerbosityLevel.ALWAYS)
            message("Creating directory manually as fallback...", MessageType.INFO, VerbosityLevel.EXTRA_VERBOSE)
            self.agent_directory.mkdir(parents=True, exist_ok=True)
            message(f"✓ Created {self.agent_directory}", MessageType.SUCCESS, VerbosityLevel.ALWAYS)

    def update(self, config: dict) -> None:
        """Update Claude/Cursor configuration from hierarchical repositories.

        Args:
            config: Configuration data with hierarchy and repo objects
        """
        # Initialize Claude agent directory (first time only)
        self._initialize()

        # Use the generic merge_configurations from AbstractAgent
        self.merge_configurations(config)

